### ISSUE TITLE
PageImpl deserialization breaks when Categories are set on the page

### ISSUE THREAD

**Issue by RaimondKempees** [sdl/dxa-web-application-java#1]
See: http://tridion.stackexchange.com/questions/12815/error-after-applying-metadata-with-category-on-page

Fix:

In `org.dd4t.contentmodel.impl.PageImpl`, change this line:

    @JsonProperty("Categories")
    private List<Category> categories;

Into this line:

    @JsonProperty("Categories") @JsonDeserialize(contentAs = CategoryImpl.class)
    private List<Category> categories;

**Comment by azarakovsky** [comment]
Fixed in v1.2
