### ISSUE TITLE
Link resolving doesn't use page context

### ISSUE THREAD

**Issue by willprice76** [sdl/dxa-web-application-java#104]
If you have a component that is used on more than one page, Tridion dynamic linking has logic which means that you get a resolved URL to the 'closest' page using proximity logic (see docs: https://docs.sdl.com/LiveContent/content/en-US/SDL%20Web%20Cloud-v1/GUID-F9F52365-2ABE-4C1E-A50C-3D4CA4F84989). On code level this requires that you pass the context page tcm uri to the com.sdl.web.api.linking.ComponentLinkImpl.getLink method call. 

This capability is not built into the DXA TridionLinkResolver class, which does not have the concept of the context page. So if you request a page which contains content with component links from the DXA model service, the links will not be resolved using the proximity logic in the Tridion docs.

**Comment by rpannekoek** [comment]
Internal ID (for tracking purposes): CRQ-12780

**Comment by rpannekoek** [comment]
Incorporated in DXA 2.2
