### ISSUE TITLE
MIME Types missing

### ISSUE THREAD

**Issue by sultansoy** [sdl/dxa-web-application-java#109]
Hi. There're many types not included in your MimeUtils.
For example woff and woff2 for fonts. So I can't use fonts as static resources on web presentation server.
I fix this problem with reflection:
`try {
            Field field = MimeUtils.class.getDeclaredField("MIME_TYPES");

            field.setAccessible(true);

            HashMap<String, String> map = (HashMap<String, String>) field.get(null);

            map.put("woff2", "application/font-woff2");

            map.put("woff", "application/font-woff");

        } catch (NoSuchFieldException | IllegalAccessException e) {

            e.printStackTrace();

        }`
But I think it's not good practice. I will create pull request with added fields, but also I want to add static method, which will recieve 2 arguments, verify mime type and put it in the map

**Comment by jajimene** [comment]
#101

**Comment by rpannekoek** [comment]
Internal Issue ID (for tracking purposes): CRQ-12809

**Comment by rpannekoek** [comment]
Incorporated in DXA 2.2
