### ISSUE TITLE
Correct branch or Tag of version 2.0

### ISSUE THREAD

**Issue by fdvalencia** [sdl/dxa-web-application-java#119]
I’m trying to download code version 2.0.0 so I can apply a fix, but I can see that this project has 2 branches that states that is release 2.0

release/2.0 -> this has pom with version 2.0.3
origin/release/2.0 -> this one has version 2.0.1

so, it’s quiet confusing,

there is also a TAG called DXA_2.0_Release
this one has the correct version in the pom, but when I run the tests it fails

so, I would like to have a branch/tag/commit that points to the version complied and uploaded to maven so I can have a reliable code where I could put my fix

thanks

**Comment by rpannekoek** [comment]
This is how our branches/releases work in general:

- Each release gets a tag (incl. interim pre-releases, GA releases and hotfix releases)
- Each major/minor release gets a branch
- When we do hotfixes, the code changes are merged into the appropriate release branch (so no separate branch for each hotfix release)

So, concretely, this means:
- The `release/2.0` branch represents the DXA 2.0 release plus all subsequent hotfix releases (at the time of writing, hotfix release 2.0.3 is the latest)
- If (for whatever reason) you want to get the source code of DXA 2.0 excluding hotfixes ("2.0.0"), you can use the `DXA_2.0_Release` tag.

The `origin/release/2.0` branch was a mistake and has been removed already.

I hope this clarifies things a bit?

**Comment by fdvalencia** [comment]
Hi Rick,

thanks for the clarification
