### ISSUE TITLE
 Link Schema doesn't resolve to support document (multimedia) links in DXA

### ISSUE THREAD

**Issue by hemraj84jain** [sdl/dxa-web-application-java#13]
We can link the multimedia document in the Link schema and could see the reference in Broker DB, but the Multimedia link is not resolved in DXA 1.2 Java.

Below is the reason and the fix:

We have different type of STRATEGY in which the links are resolved as Binary link, Component link , or page link in DXA.

We have implementation class `TridionLinkResolver.java` implements `LinkResolver` which has the methods `resolveLink` overloaded with two and three arguments, the third argument `boolean resolveToBinary` is the key to resolve the links as binary.

The `ComponentLinkFieldConverter.java` is the class and the method `createComponentLink` where it invokes the `TridionLinkResolver.resolveLink` with two arguments method as below:

**Existing Code:**

```
final String url = linkResolver.resolveLink(componentId, null);
```

it does not check STRATEGY to resolve as Binary or Component link,

**Code Change** required to check for multimedia and resolve that as binary as below

```
String url = "";

if(null != component && null != component.getComponentType() && component.getComponentType().name().equalsIgnoreCase("Multimedia")){
    // pass true as third parameter to resolve as binary
    url = linkResolver.resolveLink(componentId, null,true);
}
else{
    url = linkResolver.resolveLink(componentId, null);
}
```

**Comment by rpannekoek** [comment]
TSI-1310 (internal issue ID for tracking purposes)

**Comment by rpannekoek** [comment]
Indeed, links to (MM) Components are resolved to Pages if you map the Component Link to a property of type `String` or `Link`.  But if you map to a subclass of `MediaItem`  (e.g. `Image`), you get access to the Binary URL. 

Would this be a solution for your requirements?

**Comment by rpannekoek** [comment]
After further analysis, we decided to keep this functionality, because it provides more flexibility:

- If you want a MM Component Link to resolve to the URL of the MM Component's Binary, you should map it to a subclass of `MediaItem`
- If ypu want a MM Component Link to resolve to the URL of a Page containing the MM Component, ypu should map it to class `Link` or `String`.
