### ISSUE TITLE
XPM Device preview does not work with DXA.Java

### ISSUE THREAD

**Issue by NiclasCedermalm** [sdl/dxa-web-application-java#16]
When entering device preview in XPM on a DXA.Java site will cause stack traces. Of some reason wrong action is triggered in the page controller: handleGetPageFormatted()
A work around is to comment this action and then the correct action ( handleGetPage() ) is triggered when entering device preview. So there must be some issue with the headers sent when entering device preview. My guess is the ACCEPT header (one example sent by XPM device preview: Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8).

**Comment by jhorsman** [comment]
The headers thing sounds familiar: https://github.com/sdl/dxa-web-application-java/issues/8

**Comment by ronnierap** [comment]
Yes it's indeed fixed by PullRequest #18

**Comment by jhorsman** [comment]
Ronnie's PR #18 resolved the issue (we tested it).

I think your guess 
> My guess is the ACCEPT header (one example sent by XPM device preview: Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,/;q=0.8). 

is not correct because the `Accept: text/html` should be handled correctly in the old situation.

**Comment by jhorsman** [comment]
XPM Device Preview does not send an Accept header. In fact it only sends the Host, Connection Cookie and User-Agent headers.

The XPM Device preview failed beause without Accept header issue #8  occurs.

**Comment by azarakovsky** [comment]
https://github.com/sdl/dxa-web-application-java/pull/19 is merged
