### ISSUE TITLE
Accessing wrong controller method when using Compatibilty View in IE

### ISSUE THREAD

**Issue by ronnierap** [sdl/dxa-web-application-java#17]
When in IE and using for e.g. compatibility view for IE 8. The wrong method is being triggerd.

```java
@RequestMapping(method = RequestMethod.GET, value = "/**", produces = {MediaType.TEXT_HTML_VALUE})
public String handleGetPage(HttpServletRequest request) throws Exception {
    // removed logical code
}

@RequestMapping(method = RequestMethod.GET, value = "/**", produces = {"application/rss+xml", MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_ATOM_XML_VALUE})
public ModelAndView handleGetPageFormatted() {
   // removed logical code
}
```

**Comment by ronnierap** [comment]
When in IE and using for e.g. compatibility view for IE 8. The wrong method is being triggered.

To fix this add the `MediaType.ALL_VALUE` to the first method
```java
@RequestMapping(method = RequestMethod.GET, value = "/**", produces = {MediaType.TEXT_HTML_VALUE, MediaType.ALL_VALUE})
public String handleGetPage(HttpServletRequest request) throws Exception {
    // removed logical code
}
```

**Comment by jhorsman** [comment]
I verified this.  The compatibility view issue in IE is indeed related to the Accept headers. With the fix proposed by Ronnie the DXA page controller will return the following formats.

Accept header: 
* `application/json`  retruns a JSON feed
* `application/atom+xml` returns an ATOM feed
* `application/rss+xml` returns an RSS feed
* `text/html` and all other values return HTML


This behaviour can be overridden by the ?format parameter
* `http://localhost:9080?format=json`
* `http://localhost:9080?format=atom`
* `http://localhost:9080?format=rss`
* `http://localhost:9080?format=xml` returns HTML
* other ?format parameters are ignored

**Comment by rpannekoek** [comment]
Behavior described by Jan sound like how it should be. Can you submit a Pull Request for the suggested change on the develop branch?

**Comment by Jasmeet0108** [comment]
Hi 
I have added the fix added by Ronnie but when I am hitting URL with postmaster tool on chrome and giving content-type as "application/json" even then I am getting HTML response.

Request is not reaching the second method 
@RequestMapping(method = RequestMethod.GET, value = "/**", produces = {"application/rss+xml", MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_ATOM_XML_VALUE})
    public ModelAndView handleGetPageFormatted()


After debugging further when I changes the produces to consume along with Ronnie fix. It seem to be working fine for me. Kindly suggest if this is correct?

**Comment by azarakovsky** [comment]
https://github.com/sdl/dxa-web-application-java/pull/19 is merged
