### ISSUE TITLE
The application scanner has detected a vulnerability from DXA: "Path Traversal from URI".

### ISSUE THREAD

**Issue by sivasanikommu** [sdl/dxa-web-application-java#180]
Using DXA version 2.2.18.

The application scanner has detected a vulnerability from DXA: "Path Traversal from URI".
This originates from the following method:
com.sdl.dxa.tridion.content.GenericStaticContentResolver.getStaticContentFileByPath(GenericStaticContentResolver.java:78)

Just wanted to check whether you are already aware of this vulnerability and whether a fix is available.

**Comment by marksaunders** [comment]
Was this resolved or the source tracked down?

**Comment by dxasupport** [comment]
This has been addressed in release 2.2.32.
