### ISSUE TITLE
Metadata fields in Multimedia components are not set in MediaItem object - Causing accessibility problem

### ISSUE THREAD

**Issue by Jasmeet0108** [sdl/dxa-web-application-java#20]
While analysing code I found that if we set metadata fields in Multimedia components then its not getting populated in MediaItem. 

To fix this in we need to create variable in MediaItem to store metadata fields that can be used further.

This is especially required from Accessibility purpose where we set Alt text in case of images.

To extract metadata, add new method getMetaData in EntityBuilderImpl.java

and add this line in method createEntity(Component component, Localization localization, Class<? extends AbstractEntityModel> entityClass, SemanticSchema semanticSchema)
            throws ContentProviderException {
.
.
.
mediaItem.setMetaData(this.getMetaData(component.getMetadata()));

/**
	 * This method extracts Metadata rom components
	 * @param metadata
	 * @return
	 */
	private Map<String, String> getMetaData(Map<String, Field> inputMetadata) {
		Map<String, String> metaData = new HashMap<String, String>();
		
		if (null != inputMetadata) {
			Set<String> keys = inputMetadata.keySet();
			for(String key: keys) {
				Field field = inputMetadata.get(key);
				
				if (null != field && null != field.getValues()) {
					if (!field.getValues().isEmpty()) {
						metaData.put(key, field.getValues().get(0).toString());
					}
				}
				
			}		
		}
		return metaData;
	}

**Comment by rpannekoek** [comment]
Hi, Jasmeet0108.  The idea is that DXAs semantic mapping can be used to map MM Component metadata fields to `MediaItem`-derived View Model properties.  So, you can create your own `MediaItem` subclass (or, for example, `Image` subclass) with additional properties which are mapped to MM Component fields.  Will that be sufficient for your use cases?  Note that Image Alternate Text is already supported on the Core `Image` View Model (obtained from altText metadata field in CM).
