### ISSUE TITLE
DXA1.3: Compilation error when using existing DD4T JARs in local Maven repository

### ISSUE THREAD

**Issue by NiclasCedermalm** [sdl/dxa-web-application-java#22]
I found an issue when compiling the new DXA1.3 locally. I had since before a local version of DD4T 2.0.2-DXA in my local Maven repository (installed via the DXA1.2 ZIP). This gives me the following errors when I'm try to compile DXA1.3:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project dxa-tridion-provider: Compilation failure: Compilation failure:
[ERROR] /Users/nic/Develop/Projects/SDL/DXA/code/DXA.Java/dxa1.3/dxa-web-application-java/dxa-framework/dxa-tridion-provider/src/main/java/com/sdl/webapp/config/TridionSpringConfig.java:[64,82] incompatible types: java.lang.Class<org.dd4t.contentmodel.impl.ComponentPresentationImpl> cannot be converted to java.lang.Class<org.dd4t.contentmodel.ComponentPresentation>
[ERROR] /Users/nic/Develop/Projects/SDL/DXA/code/DXA.Java/dxa1.3/dxa-web-application-java/dxa-framework/dxa-tridion-provider/src/main/java/com/sdl/webapp/config/TridionSpringConfig.java:[65,74] incompatible types: java.lang.Class<org.dd4t.contentmodel.impl.ComponentTemplateImpl> cannot be converted to java.lang.Class<org.dd4t.contentmodel.ComponentTemplate>
[ERROR] /Users/nic/Develop/Projects/SDL/DXA/code/DXA.Java/dxa1.3/dxa-web-application-java/dxa-framework/dxa-tridion-provider/src/main/java/com/sdl/webapp/config/TridionSpringConfig.java:[66,58] incompatible types: java.lang.Class<org.dd4t.contentmodel.impl.ComponentImpl> cannot be converted to java.lang.Class<org.dd4t.contentmodel.Component>
[ERROR] /Users/nic/Develop/Projects/SDL/DXA/code/DXA.Java/dxa1.3/dxa-web-application-java/dxa-framework/dxa-tridion-provider/src/main/java/com/sdl/webapp/config/TridionSpringConfig.java:[67,50] incompatible types: java.lang.Class<org.dd4t.contentmodel.impl.BaseField> cannot be converted to java.lang.Class<org.dd4t.contentmodel.Field>`

I get the same error when doing the same on one of my Windows AWS servers where I've compiled DD4T 2.0.2-DXA myself. I did a file compare and the JARs are indeed different between DXA1.2 and DXA1.3.

The workaround is however dead simple, just remove old DD4T 2.0.2-DXA from local Maven repository and recompile. Then it works fine again. So the question is if DD4T 2.0.2-DXA has been modified since DXA1.2? Should it not get a new version number then?

**Comment by azarakovsky** [comment]
Hi Niclas. 

Indeed, you're right that custom DD4T has been changed, and that it should've got a new version. Unfortunately, that has not happened, and we indeed deliver a new version of custom DD4T with the same version. The right version is not in local-project-repo, btw, you don't have to rebuild custom DD4T.

Your workaround is right.

This will be gone in the next release.

**Comment by rpannekoek** [comment]
Fixed in DXA 1.4
