### ISSUE TITLE
DXA 1.3 release (dxa-parent) not available in public Maven repositories

### ISSUE THREAD

**Issue by mikepercivalbb** [sdl/dxa-web-application-java#27]
Hi all,

It appears that dxa-parent v1.3.0 isn't available in public maven repos so in order to build and compile the release, I need to grab the git code for the release, build dxa-parent then add to local maven before I can use the release (incl. build from archetype)

Is there a plan to add dxa-parent 1.3 to public maven repos? It looks like dxa-parent 1.2 is available.

**Comment by azarakovsky** [comment]
Hi,
Perhaps you are looking for this http://search.maven.org/#artifactdetails%7Ccom.sdl.dxa%7Cdxa-parent%7C1.3.0%7Cpom

**Comment by mikepercivalbb** [comment]
Hmm, was that there a earlier this week? All requests to retrieve the package from previous builds were failing in retrieving the package from central maven. I've removed the local maven package I built and now it seems to be getting the dxa-parent from the public maven repo and working correctly.
Sorry to have questioned it!

**Comment by azarakovsky** [comment]
It appeared on Central on 15 Feb together with the rest of artifacts. It seems that you have had your local repository in a broken state. Good that the issue is solved :)
