### ISSUE TITLE
pom.xml refers to DXA 1.3.0-SNAPSHOT but doesn't exist in Maven central

### ISSUE THREAD

**Issue by ds23pallas** [sdl/dxa-web-application-java#28]
The pom.xml included here requests DXA v1.3.0-SNAPSHOT, however this does not exist in Maven central - the version in Maven central is 1.3.0 http://repo.maven.apache.org/maven2/com/sdl/dxa/dxa-parent/1.3.0/dxa-parent-1.3.0.pom

It seems that this is a mismatch as attempting to build this solution without first adding 1.3.0-SNAPSHOT to the local Maven repo fails.

**Comment by azarakovsky** [comment]
Please use the release branch instead. https://github.com/sdl/dxa-web-application-java/tree/release/1.3
Or a release tag which is set on that branch. https://github.com/sdl/dxa-web-application-java/tree/DXA_1.3.0_Release

Branch 'master' is not a release branch, and is considered just as stable version, so it indeed has a SNAPSHOT dependencies. At this particular moment it represents the sate of the release/1.3 branch right before release.

**Comment by ds23pallas** [comment]
Thanks - it works on release/1.3 without having anything in the local repo.
