### ISSUE TITLE
Test failure in dxa-common-api while execution of Maven build

### ISSUE THREAD

**Issue by alexrwd** [sdl/dxa-web-application-java#31]
dxa-common-api cannot be built because of test failures while Maven build:
"Results :

Failed tests:   shouldGetClaimValues(com.sdl.webapp.common.api.contextengine.ContextClaimsTest): expected:<str[1]> but was:<str[2]>

Tests run: 91, Failures: 1, Errors: 0, Skipped: 0"

**Comment by azarakovsky** [comment]
Against which branch do you run Maven? Which is your Maven and JDK versions?

**Comment by alexrwd** [comment]
Branch - Master, Maven - 3.2.3, Java - 1.7.0_67

**Comment by azarakovsky** [comment]
Fixed. Will appear on github/develop and github/master in a while.

As a temporal solution please either switch to Java 8 or @Ignore this particular test.
