### ISSUE TITLE
 Images with spaces in the file name result in broken image on the page

### ISSUE THREAD

**Issue by jhorsman** [sdl/dxa-web-application-java#32]
Repro steps:

*    Create image component with a space in the file name
*    Add image component to a page
*    Publish page
*    Verify image is broken
*    Examine image url, has %20 properly encoded

This is the counterpart of the same issue in DXA .NET https://github.com/sdl/dxa-web-application-dotnet/issues/17

Reproduced on Tridion 2013 SP1 and DXA 1.2.1.

**Comment by jhorsman** [comment]
Tested with the built in DD4T image resizing, not tested with CID profile.

**Comment by jhorsman** [comment]
com.sdl.webapp.tridion.DefaultProvider.getStaticContentFile() throws an error when the image URL has a %20 encoded space.

It is findBinaryVariant() who takes the decoded url (with space) and passes it as a path to the Content Delivery DAO. The findBinaryVariant() should do URL encoding first.

		09:32:42.245 [http-bio-9080-exec-3] ERROR c.s.w.c.controller.PageController - Exception while processing request for: /zorgmakelaar/media/beautiful landscape_tcm7-3608_w1024_h311_n.jpg
		com.sdl.webapp.common.api.content.StaticContentNotFoundException: No binary variant found for: [7] /zorgmakelaar/media/beautiful landscape_tcm7-3608.jpg
			at com.sdl.webapp.tridion.DefaultProvider.getStaticContentFile(DefaultProvider.java:301) ~[dxa-tridion-provider-1.2.jar:1.2]
			at com.sdl.webapp.tridion.DefaultProvider.getStaticContent(DefaultProvider.java:260) ~[dxa-tridion-provider-1.2.jar:1.2]

**Comment by azarakovsky** [comment]
@jhorsman this is known issue, and it is already fixed in an upcoming release.

**Comment by rpannekoek** [comment]
Fixed in DXA 1.4
