### ISSUE TITLE
Include pages are always loaded with a view from the core module

### ISSUE THREAD

**Issue by jhorsman** [sdl/dxa-web-application-java#34]
Include pages in DXA 1.3 JAVA (and DXA 1.2) are added on the page as a region. The region name is based on the page name (the name set on the page item in the Content Manager). The region view used is based on the page name as well.

The issue is that the module/area name in is not used. So if the name of an include page is set to module:view (i.e. my-module:header), then the module part is removed, and the view is loaded from the core. So instead of "my-module:header" the "core:header" view is loaded.

You can imagine that this subtile detail costs quite a bit of troubleshooting time when both my-module and the code module have a header view. ;)

The behaviour is implemented in `com.sdl.webapp.tridion.mapping:getRegionFromIncludePage` [source](https://github.com/sdl/dxa-web-application-java/blob/master/dxa-framework/dxa-tridion-provider/src/main/java/com/sdl/webapp/tridion/mapping/PageBuilderImpl.java), but why? I cannot see any reason why to ignore the module name.

**Comment by jhorsman** [comment]
Answering my own question:

> The behavior is implemented in com.sdl.webapp.tridion.mapping:getRegionFromIncludePage source, but why? I cannot see any reason why to ignore the module name.

For the _region name_ the module name should be ignored. Region names are unqualified, meaning they are not for a specific module. The _region view_  however is qualified. In getRegionFromIncludePage the two are mixed up. The unqualified _region name_ is used as _region view_  which defaults to the core region.

In the end the _page title_ "My-Module:Header" should be translated to _region name_ "Header" and _region view_ "My-Module:Header".

This is addressed in pull request https://github.com/sdl/dxa-web-application-java/issues/35

**Comment by azarakovsky** [comment]
Merged. Will be in 1.5.0.

**Comment by rpannekoek** [comment]
Fixed in DXA 1.5.
