### ISSUE TITLE
Session-scoped Spring beans will make the site break (DXA1.4/SDL Web 8)

### ISSUE THREAD

**Issue by NiclasCedermalm** [sdl/dxa-web-application-java#39]
When using session-scoped Spring beans in DXA 1.4 and SDL Web 8.1.1 will make the site break. As soon there is a session bean active on the session nothing will work on the site.

The exception I got is the following:
`java.lang.UnsupportedOperationException: Attempted to serialize java.lang.Class: javax.annotation.PostConstruct. Forgot to register a type adapter?
	com.google.gson.internal.bind.TypeAdapters$1.write(TypeAdapters.java:67)
	com.google.gson.internal.bind.TypeAdapters$1.write(TypeAdapters.java:61)
	com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
	com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:99)
	com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:219)
	com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
	com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:96)
	com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:60)
	com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
	com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:99)
	com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:219)
	com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
	com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:99)
	com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:219)
	com.google.gson.internal.bind.ObjectTypeAdapter.write(ObjectTypeAdapter.java:107)
	com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
	com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
	com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
	com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
	com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
	com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
	com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
	com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:99)
	com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:219)
	com.google.gson.Gson.toJson(Gson.java:600)
	com.google.gson.Gson.toJson(Gson.java:579)
	com.google.gson.Gson.toJson(Gson.java:534)
	com.google.gson.Gson.toJson(Gson.java:514)
	com.sdl.web.ambient.serialization.ClaimStoreSerializer.serialize(ClaimStoreSerializer.java:30)
	com.sdl.web.ambient.serialization.ClaimStoreSerializationUtil.serializeClaimStore(ClaimStoreSerializationUtil.java:38)
	com.sdl.web.ambient.client.AmbientClientFilter.performADFAction(AmbientClientFilter.java:35)
	com.sdl.web.ambient.client.AmbientClientFilter.processStartEvents(AmbientClientFilter.java:78)
	com.tridion.ambientdata.web.AbstractAmbientDataServletFilter.doFilter(AbstractAmbientDataServletFilter.java:291)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)`

The problem is that the ADF client filter (com.sdl.web.ambient.client.AmbientClientFilter) will serialize the whole claim store including all session attributes (taf:session:attributes) and pass it to the CIS micro service layer. When having some active Spring session beans will make the serialization fail with above error. Should not the filter only serialize those claims that are marked as forwarded in the 'cd_ambient_conf.xml' file? Or at least only claim values that are serializable.

**Comment by rpannekoek** [comment]
Seems to be an issue in the ADF client filter; under investigation.

**Comment by rpannekoek** [comment]
This has been confirmed to be an issue in 8.1.1 ADF client filter and is scoped for fixing in 8.1.2.

**Comment by rpannekoek** [comment]
Not an issue in DXA code base.
