### ISSUE TITLE
Unable to pass HTML classes to Embedded Image (RTF)

### ISSUE THREAD

**Issue by jarnohenneman** [sdl/dxa-web-application-java#41]
In whitelabel design under Complex Article (http://sdl.github.io/dxa-html-design/content-types/complex-article.html) - Other formatting options its possible to position an image in text left, center or right alinged. 

    <div>
      <p><img class="pull-left" src="/dxa-html-design/system/assets/images/teaser/balloons.jpg" alt="Floating left image">
      You can align inline elements with <strong>pull-left</strong>, 
      <strong>pull-right</strong> and <strong>center-block</strong> classes. 
      Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>

The align inline elements with `pull-left`, `pull-right` and `center-block` are not working.

Changes:

`com.sdl.webapp.common.api.model.entity.Image`
Remove `widthFactor=100%`

**MediaItem.java**

    public void readFromXhtmlElement(Node xhtmlElement) {
        this.setHtmlClasses(xhtmlElement.getAttributes().getNamedItem("class").getNodeValue());
    }

**Comment by rpannekoek** [comment]
Fixed in DXA 1.5.
