### ISSUE TITLE
ADF and XPM Session Preview does not work on DXA 1.4 JAVA

### ISSUE THREAD

**Issue by jhorsman** [sdl/dxa-web-application-java#44]
DXA 1.4 JAVA does not load the ADF filter. Because of this XPM Session Preview does not work.

* I did not test this explicitly with older DXA versions
* The develop branch has a [`XpmPreviewWebConfiguration`](https://github.com/sdl/dxa-web-application-java/blob/99caa994827ce31a2bbb18460f77b4d757dead50/dxa-framework/dxa-web8-provider/src/main/java/com/sdl/webapp/tridion/config/XpmPreviewWebConfiguration.java) in the dxa-web8-provider project. This bit of code works in my DXA 1.4 based webapp so I think this issue will be resolved in DXA 1.5.
* The `/admin/adf-claims` controller from DXA kickstart's [admin controller](https://github.com/NiclasCedermalm/dxa-kickstart/blob/master/application/dxa-webapp/src/main/java/com/sdl/webapp/kickstart/controller/AdminController.java) and [all-claims view](https://github.com/NiclasCedermalm/dxa-kickstart/blob/master/application/dxa-webapp/src/main/webapp/WEB-INF/Views/Admin/adf-claims.jsp) helped me to test weather ADF is alive.

**Comment by azarakovsky** [comment]
You should register ADF filter to enable ADF. Even if DXA doesn't do it automatically and web.xml with registration is not in a package, you still can do it manually and therefore fix the issue. In 1.5 XPM and ADF are managed by properties "dxa.web.xpm.enabled" and "dxa.web.adf.enabled", but you still can manage them manually is you want.
