### ISSUE TITLE
Override the 500 Error Page with a custom one

### ISSUE THREAD

**Issue by kunalshetye** [sdl/dxa-web-application-java#46]
Hi,

The 500 Error Custom page is embedded the dxa core module (\META-INF\resources\WEB-INF\Views\Shared\Error\ServerError.jsp) and there is no direct way of overriding it.

A workaround has been mentioned here:
http://tridion.stackexchange.com/questions/14889/customize-500-error-page-in-dxa-1-4-java

Is is possible for the user to add a static page in the Web Application that the dxa framework would redirect to if there's an 500 Error that occurs in the dxa framework?

Regards,
Kunal

**Comment by rpannekoek** [comment]
Addressed in DXA 1.6; these Views are not part of the Web Application instead of the Core Module.
