### ISSUE TITLE
Multiple <html>,<head> and <body> tags when using dxa entities in DXA1.2

### ISSUE THREAD

**Issue by Jasmeet0108** [sdl/dxa-web-application-java#5]
While Rendering dxa entities tag in DXA-1.2 multiple body, head and html tags are being rendered 
Refer below Source code snippet from page.

![issue_list](https://cloud.githubusercontent.com/assets/16399692/11953318/78ddb006-a89f-11e5-8ada-4def60497e04.jpg)

While investigating issue I found that changes are required in AbstractMarkupTag-->processInclude() method when its converting the renderHtml object into "ParsableHtmlNode" object which is intern adding html tags by using "Jsoup.parse()". changes seems to be working in my local

**Comment by NiclasCedermalm** [comment]
I have seen this issue at some rare situations. It normally occur when the region or component presentation view is not surrounding by one single HTML tag. One easy fix is to just surrounding your view code with a div tag and then the additional html-tags should disappear. So the HTML parse functionality needs to be improved to handle this kind of situations.

**Comment by bkoopman** [comment]
For XPM support we need to have at least a single HTML tag in each view, because otherwise we cannot place the `${markup.region(region)}` or `${markup.entity(entity)}` anywhere. But sounds like we should indeed handle it to prevent it from happening in case a view does not have any HTML.

**Comment by bkoopman** [comment]
Issue is expected behavior at current, but it makes sense to document the fact that views should have at least a top level HTML element for use of XPM, semantic markup and general semantic HTML correctness.

**Comment by rpannekoek** [comment]
Documented as "Known Issue" in DXA 1.5.
