### ISSUE TITLE
Link resolver doesn't use page context when resolving component links

### ISSUE THREAD

**Issue by HaraldHoffelinck** [sdl/dxa-web-application-java#54]
We are seeing the following issue.

A page contains a component presentation that contains component links to other CP's on the same page (this is related to the issue about [in page navigation](https://github.com/sdl/dxa-web-application-java/issues/53)
The link resolver resolves those links to the same page, except if the component linked to is also used on a different page. 

Ideally, the page context should be used when resolving component links, so it follows the link resolving logic specified in the [documentation](http://docs.sdl.com/LiveContent/content/en-US/SDL%20Web-v1/GUID-F9F52365-2ABE-4C1E-A50C-3D4CA4F84989)

**Comment by bkoopman** [comment]
In general link resolving is only predictive when you use the correct Component Template priorities, from what you describe I don't see a direct issue yet. Can you update with some more detail about the issue you see? From what page are you linking and to what CP do you expect it to go (what are the CT priorities of the CPs invlved) and what is actually happening?

**Comment by HaraldHoffelinck** [comment]
What is happening is this : 
We currently have a homepage (page A) with a CP with three component links to three different components that are also on the same page. 
One of these three components is also placed as a CP on a different page (page B), using the same CT (so the linking priorities are the same).

The link resolver resolves the link to those two CP's to the same page (page A), but for the third, it resolves the link to the different page (page B).

I think what happens is that, as both page A and page B are in the same structure group, the link resolver logic gives both links the same score, but then finally uses the 'page creation date' to determine the url to link to.

**Comment by rpannekoek** [comment]
TSI-1939 (internal issue ID for tracking purposes)

**Comment by rpannekoek** [comment]
Internal Issue ID (for tracking purposes): CRQ-12780

**Comment by rpannekoek** [comment]
Incorporated in DXA 2.2
