### ISSUE TITLE
DXA does not set cache headers

### ISSUE THREAD

**Issue by jhorsman** [sdl/dxa-web-application-java#6]
DXA JAVA does not set instructions in the cache headers. Result is that Chome and Firefox do cache resources like images, CSS and JavaScript, but IE does not.

The webapp should be more explicit:
* set cache headers on all responses so that browsers will interpret cache in the way you intend
* cache design resources for a long time (everything in the versioned /system/v0.75 url)
* use content-based (Last-modified or ETag) for other resources; the server can work out if those resources changed
* expicitly not cache pages; since they could change due to server side responsiveness and content queries.

An additional improvement of a different order (bonus points for that) would be for DXA to figure out if a page changed and return a 304 if the page and it's content did not change.

The .NET version seems to explicitly disable all caching: https://github.com/sdl/dxa-web-application-dotnet/blob/master/Sdl.Web.Mvc/Controllers/NoCacheAttribute.cs

**Comment by bkoopman** [comment]
The `NoCacheAttribute.cs` just gives us the use of a `[NoCache]` attribute on the controllers in DXA .NET, it isn't used on any of the core controllers like Page, Region and Entity, only on the AdminConrtolelr (which is part of the Site Project).

**Comment by jhorsman** [comment]
@bkoopman I see, so the attribute is available but not used. I guess that means that DXA .NET also does not set cache instructions in the response headers.

**Comment by ArjanvanRooijen** [comment]
In the CXC demo we (Philippe) added caching for the system files since these are versionized anyway and should be cached clientside. .Net version blocks this in Java version there is no cache instruction so some browers do like @jhorsman mentioned

Sdl.Web.Mvc\Statics\StaticContentModule.cs

{code:c#}
if (urlPath.StartsWith("/system/assets/"))
                            {
                                Log.Debug("Setting cache expiration to allow browser caching.");  
                                response.Cache.SetExpires(DateTime.UtcNow.AddDays(10));
                                response.Cache.SetCacheability(HttpCacheability.Private);
                                response.Cache.SetMaxAge(TimeSpan.FromDays(10));
                            }
{code}

**Comment by rpannekoek** [comment]
Fixed in DXA 1.3
