### ISSUE TITLE
noTopologyManager parameter is not working

### ISSUE THREAD

**Issue by gdeheul** [sdl/dxa-web-application-java#60]
`noTopologyManager` parameter is not working when importing Publications and content items.  The import script is still looking for standard values defined in the `ttm-prepare.ps1` script (version SDL DXA Java 1.4)

**Comment by rpannekoek** [comment]
The meaning of the `noTopologyManager` parameter is that it doesn't try to create TTM Mappings for the DXA Example Site (and hence doesn't require TTM cmdlets to be available on the machine where the `cms-imports.ps1` script is run).

The issue referred to here is that the DXA BPTs require specific Topology Types to be present in TTM. This is unrelated to the parameter and not a bug.

**Comment by gdeheul** [comment]
Ok fair enough,  but shouldn't there be an parameter which allows you to use you own topology without using the ttm-prepare and cleaning up the entries from ttm-prepare afterwards?

**Comment by rpannekoek** [comment]
See http://tridion.stackexchange.com/questions/15470/install-dxa-for-web-8-with-different-target-name
