### ISSUE TITLE
Null reference exception when a region is added in a component presentation on the page and in an include of that same page

### ISSUE THREAD

**Issue by HaraldHoffelinck** [sdl/dxa-web-application-java#62]
If a page contains a component presentation with a certain region name, and an include of that page contains the same region name, then we get a null reference exception in the page builder.

**Comment by rpannekoek** [comment]
TSI-2006 (internal issue ID for tracking purposes)

**Comment by azarakovsky** [comment]
@HaraldHoffelinck we were not able to reproduce the issue on 1.5 but your code change seems OK, so I merged it in 1.7. Hope it solves the issue.

I would appreciate if you can provide details how to reproduce it.

**Comment by rpannekoek** [comment]
Fixed in DXA 1.7
