### ISSUE TITLE
Default multimedia not been handled in DXA1.2

### ISSUE THREAD

**Issue by Jasmeet0108** [sdl/dxa-web-application-java#7]
DefaultMultimedia schema is not working after moving to DXA1.2. 

After analysing further I found that compared with older version we have specific Multimedia link field converter for multimedia items whereas in newer version it in incorporated in ComponentLinkFieldConverter
but since defaultmultimedia component is giving model targetClass as "DefaultMultiMedia" which is not present in DXA1.2 it is failing.
i.e. while retrieving values for component it is expected a model class with Name "DefaultMultiMedia"
Object retval = builder.createEntityModel(component, localization, (Class<AbstractEntityModel>) targetClass);

**Comment by bkoopman** [comment]
Have you completely migrated everything to DXA 1.2, CM side, views and DXA core? Since when that is done, you should not have any issues. Please note that there is no specific upgrade path between the DXA Java pre release and DXA 1.2, since 1.2 is the first official Java release of DXA.

**Comment by Jasmeet0108** [comment]
Closing issue after updating new TBB. issue is resolved
