### ISSUE TITLE
Versioned CSS/JS paths don't work when the HTML design is part of the web app

### ISSUE THREAD

**Issue by willprice76** [sdl/dxa-web-application-java#75]
If you choose to manage your HTML design outside of the CMS (so put it in the web app instead of publishing it from the CMS) and use the `markup.versionedContent` helper to output a versioned path to the design files (to ensure that browser cache is not an issue when a new version is released) then you get a blank response. What should happen is the web app should internally strip the version number from the request and rewrite the request to the files within the web application.

So /system/v1.2/assets/css/main.css should rewrite to /system/assets/css/main.css

Similar to how it works when the HTML design is published from the CMS

**Comment by rpannekoek** [comment]
Fixed in DXA 1.8 and 2.0
