### ISSUE TITLE
sitemap.xml contains relative urls

### ISSUE THREAD

**Issue by JacquesKors** [sdl/dxa-web-application-java#76]
the SiteMapXmlController generates a sitemap.xml wth a relative path
`<loc>/index</loc>`

Thiese nodes should contain a fulliw qualified path
`<loc>http://server.domain/index</loc>`

**Comment by rpannekoek** [comment]
Internal Issue ID (for tracking purposes): CRQ-12819

**Comment by rpannekoek** [comment]
Fixed in DXA 2.2
