### ISSUE TITLE
Resource JSON not available over HTTP request

### ISSUE THREAD

**Issue by willprice76** [sdl/dxa-web-application-java#77]
If you have DXA modules with a clientside aspect (for example a module which renders some content client side) then you would need to load resources and/or config JSON via an HTTP request. It seems that this is not currently possible, as URLs such as http://site/system/resources/modulename.json give a 404. These should be accessible via HTTP.

**Comment by rpannekoek** [comment]
Internal Issue ID (for tracking purposes): CRQ-12820

**Comment by rpannekoek** [comment]
Incorporated in DXA 2.2
