### ISSUE TITLE
AbstractDefaultContentProvider: Getting page is not reliable

### ISSUE THREAD

**Issue by DominicCronin** [sdl/dxa-web-application-java#85]
https://github.com/sdl/dxa-web-application-java/blob/888343aff869806b5eceb76a2d2f9ec62e2c9d83/dxa-framework/dxa-tridion-provider/src/main/java/com/sdl/webapp/tridion/mapping/AbstractDefaultContentProvider.java#L219

This is on the 1.7 branch. I can't see it in later versions, but maybe it's been moved elsewhere, or perhaps removed altogether. I'll leave that up to people who know the code better than I do. 

The assumption in the code: 
```
                    synchronized (LOCK) {
                        if (dd4tPageFactory.isPagePublished(path, publicationId)) {
                            genericPage = dd4tPageFactory.findPageByUrl(path, publicationId);
                        } else {
                            return null;
                        }
                    }
```
seems to be that by checking isPagePublished, one can then rely on findPageByUrl to return the page object. There's some exception handling, and the possibility of returning null for some things, but if you come out of the lock section with a null genericPage, there is no check to prevent the null getting passed to modelBuilderPipeline.createPageModel. 
On my system, this happens, and in createPageModel, I get a nullReferenceException from dereferencing the genericPage parameter.

**Comment by rpannekoek** [comment]
This code is no longer used in DXA 2.0 and higher (the DXA Web App Framework works with DXA R2 Data Model rather than with DD4T APIs).
