### ISSUE TITLE
The `WebRequestContextImpl.getFullUrl()` method in in the `com.sdl.webapp.common.impl` package returns an incorrect URL.

### ISSUE THREAD

**Issue by jhorsman** [sdl/dxa-web-application-java#88]
The `WebRequestContextImpl.getFullUrl()` method in in the `com.sdl.webapp.common.impl` package returns an incorrect URL. Tested in DXA JAVA 1.7

**Problem**
The implementation looks like this. Both `getbaseURL()` and `getRequestPath()` return the relative part of the URL.

    @Override
    public String getFullUrl() {
        return getBaseUrl() + getContextPath() + getRequestPath();
    }

**Effect**
The side effect is that page metadata in the PageModel is incorrect. The `og:url` in the page metadata relies on `getFullUrl()`
        <meta name="og:url" content="http://localhost:8080/articles/movies/up/articles/movies/up">

Also the social share URL, set in the `HttpServletRequest` by the page controller relies on `getFullUrl()`.

The `getFullUrl()` is also used to resolve the `Localization` (publication id and all) based on URL. For this purpose it is not a problem to have this incorrect URL

**Example**
When browsing to http://localhost:8080/articles/movies/up the `getFullUrl()` will return http://localhost:8080/articles/movies/up/articles/movies/up 

This could be tested in `WebRequestContextImplTest`, I did not add a test yet.

**Comment by azarakovskiy** [comment]
@jhorsman it is fixed in 2.0, we're not fixing it in 1.7.

**Comment by rpannekoek** [comment]
Fixed in DXA 2.0
