### ISSUE TITLE
Errors possible in ModelBuilder if linked Multimedia not sufficiently expanded

### ISSUE THREAD

**Issue by willprice76** [sdl/dxa-web-application-java#92]
I have scenarios where the EntityModelData for a linked binary contains only the component ID. In this case the model builder should not try to create a property object for the linked entity, however currently it continues and then throws an exception for the whole process, when it tries to parse the schema Id from the EntityModelData (which is null) into a Long see the following code line:

https://github.com/sdl/dxa-web-application-java/blob/1610c7be29c038ffebf340bb8c44c5046de607cf/dxa-framework/dxa-tridion-provider/src/main/java/com/sdl/dxa/tridion/mapping/impl/DefaultModelBuilder.java#L106

The scenario where I see this is if I have a component A which has a component link to component B which links to another component C, which contains a multimedia link. I don't care about the media (or any other data for that matter) in component C, but this is causing the mapping of component A to an entity to fail completely. 

The JSON from the ModelService for this media field is:

`"media": {"$type": "EntityModelData", "Id": "519403", "LinkUrl": ""}`

**Comment by tfinez** [comment]
Is this solved in the master version?

**Comment by fdvalencia** [comment]
Hi, 
I have been inform that this issue have been solve and it should be fix for version 2.1, but I can't find this dependency in maven, ¿when is this fix going to be promoted to maven?

thanks

**Comment by rpannekoek** [comment]
Internal Issue ID (for tracking purposes): CRQ-12818

**Comment by rpannekoek** [comment]
Fixed in DXA 2.2
