### ISSUE TITLE
Only possible to embedded MediaItem entities in Rich Text fragments

### ISSUE THREAD

**Issue by willprice76** [sdl/dxa-web-application-java#93]
The ability to embed entities in Rich Text fragments is great, and can simply be made more generic to allow more than just images. See https://github.com/sdl/dxa-content-management/issues/13 for the corresponding issue to change the publishing process. Necessary is that the RichTextDataConverter can handle the case where the embedded entity is not a MediaItem, and instead tries to map it to an AbstractEntityModel. 

This is the relevant part of the code which needs to be altered.

https://github.com/sdl/dxa-web-application-java/blob/58a4fdebafc192b9a87570c684bd97d9091fdc5f/dxa-framework/dxa-tridion-provider/src/main/java/com/sdl/dxa/tridion/mapping/converter/RichTextDataConverter.java#L39

**Comment by rpannekoek** [comment]
Internal ID (for tracking purposes): CRQ-12781

**Comment by rpannekoek** [comment]
Incorporated in DXA 2.2
